name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:


permissions:
    id-token: write
    contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出当前仓库代码
        uses: actions/checkout@v4

      - name: 安装 Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - args: [--no-frozen-lockfile]

      - name: 构建文档
        run: "pnpm docs:build"

      - name: 上传并部署到Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist